package com.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Sales Representative")
	private com.solarvillage.SalesRep salesRep;
	@org.kie.api.definition.type.Label("Property")
	private com.solarvillage.Property property;
	@org.kie.api.definition.type.Label("HOA Approved")
	private java.lang.Boolean isHoaApproved;

	@org.kie.api.definition.type.Label("Created Date")
	private java.time.LocalDateTime createdDate;

	@org.kie.api.definition.type.Label("Completed Date")
	private java.time.LocalDateTime completedDate;

	@org.kie.api.definition.type.Label("Completed Status")
	private java.lang.String completedStatus;

	@org.kie.api.definition.type.Label(value = "Electrical Permit")
	private com.solarvillage.ResidentialPermit electricalPermit;

	@org.kie.api.definition.type.Label(value = "Structural Permit")
	private com.solarvillage.ResidentialPermit structuralPermit;

	public NewOrder() {
	}

	public com.solarvillage.SalesRep getSalesRep() {
		return this.salesRep;
	}

	public void setSalesRep(com.solarvillage.SalesRep salesRep) {
		this.salesRep = salesRep;
	}

	public com.solarvillage.Property getProperty() {
		return this.property;
	}

	public void setProperty(com.solarvillage.Property property) {
		this.property = property;
	}

	public java.lang.Boolean getIsHoaApproved() {
		return this.isHoaApproved;
	}

	public void setIsHoaApproved(java.lang.Boolean isHoaApproved) {
		this.isHoaApproved = isHoaApproved;
	}

	public java.time.LocalDateTime getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(java.time.LocalDateTime createdDate) {
		this.createdDate = createdDate;
	}

	public java.time.LocalDateTime getCompletedDate() {
		return this.completedDate;
	}

	public void setCompletedDate(java.time.LocalDateTime completedDate) {
		this.completedDate = completedDate;
	}

	public java.lang.String getCompletedStatus() {
		return this.completedStatus;
	}

	public void setCompletedStatus(java.lang.String completedStatus) {
		this.completedStatus = completedStatus;
	}

	public com.solarvillage.ResidentialPermit getElectricalPermit() {
		return this.electricalPermit;
	}

	public void setElectricalPermit(
			com.solarvillage.ResidentialPermit electricalPermit) {
		this.electricalPermit = electricalPermit;
	}

	public com.solarvillage.ResidentialPermit getStructuralPermit() {
		return this.structuralPermit;
	}

	public void setStructuralPermit(
			com.solarvillage.ResidentialPermit structuralPermit) {
		this.structuralPermit = structuralPermit;
	}

	public NewOrder(com.solarvillage.SalesRep salesRep,
			com.solarvillage.Property property,
			java.lang.Boolean isHoaApproved,
			java.time.LocalDateTime createdDate,
			java.time.LocalDateTime completedDate,
			java.lang.String completedStatus,
			com.solarvillage.ResidentialPermit electricalPermit,
			com.solarvillage.ResidentialPermit structuralPermit) {
		this.salesRep = salesRep;
		this.property = property;
		this.isHoaApproved = isHoaApproved;
		this.createdDate = createdDate;
		this.completedDate = completedDate;
		this.completedStatus = completedStatus;
		this.electricalPermit = electricalPermit;
		this.structuralPermit = structuralPermit;
	}

}