package com.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NewOrder implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Sales Representative")
	private com.solarvillage.SalesRep salesRep;
	@org.kie.api.definition.type.Label("Property")
	private com.solarvillage.Property property;
	@org.kie.api.definition.type.Label("Structural Permit No.")
	private java.lang.Integer structuralPermitNumber;
	@org.kie.api.definition.type.Label("HOA Approved")
	private java.lang.Boolean isHoaApproved;

	@org.kie.api.definition.type.Label("Electrical Permit No.")
	private java.lang.Integer electricalPermitNumber;

	@org.kie.api.definition.type.Label(value = "Created Date")
	private java.time.LocalDateTime createdDate;

	@org.kie.api.definition.type.Label(value = "Completed Date")
	private java.time.LocalDateTime completedDate;

	@org.kie.api.definition.type.Label(value = "Completed Status")
	private java.lang.String completedStatus;

	public NewOrder() {
	}

	public com.solarvillage.SalesRep getSalesRep() {
		return this.salesRep;
	}

	public void setSalesRep(com.solarvillage.SalesRep salesRep) {
		this.salesRep = salesRep;
	}

	public com.solarvillage.Property getProperty() {
		return this.property;
	}

	public void setProperty(com.solarvillage.Property property) {
		this.property = property;
	}

	public java.lang.Integer getStructuralPermitNumber() {
		return this.structuralPermitNumber;
	}

	public void setStructuralPermitNumber(
			java.lang.Integer structuralPermitNumber) {
		this.structuralPermitNumber = structuralPermitNumber;
	}

	public java.lang.Boolean getIsHoaApproved() {
		return this.isHoaApproved;
	}

	public void setIsHoaApproved(java.lang.Boolean isHoaApproved) {
		this.isHoaApproved = isHoaApproved;
	}

	public java.lang.Integer getElectricalPermitNumber() {
		return this.electricalPermitNumber;
	}

	public void setElectricalPermitNumber(
			java.lang.Integer electricalPermitNumber) {
		this.electricalPermitNumber = electricalPermitNumber;
	}

	public java.time.LocalDateTime getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(java.time.LocalDateTime createdDate) {
		this.createdDate = createdDate;
	}

	public java.time.LocalDateTime getCompletedDate() {
		return this.completedDate;
	}

	public void setCompletedDate(java.time.LocalDateTime completedDate) {
		this.completedDate = completedDate;
	}

	public java.lang.String getCompletedStatus() {
		return this.completedStatus;
	}

	public void setCompletedStatus(java.lang.String completedStatus) {
		this.completedStatus = completedStatus;
	}

	public NewOrder(com.solarvillage.SalesRep salesRep,
			com.solarvillage.Property property,
			java.lang.Integer structuralPermitNumber,
			java.lang.Boolean isHoaApproved,
			java.lang.Integer electricalPermitNumber,
			java.time.LocalDateTime createdDate,
			java.time.LocalDateTime completedDate,
			java.lang.String completedStatus) {
		this.salesRep = salesRep;
		this.property = property;
		this.structuralPermitNumber = structuralPermitNumber;
		this.isHoaApproved = isHoaApproved;
		this.electricalPermitNumber = electricalPermitNumber;
		this.createdDate = createdDate;
		this.completedDate = completedDate;
		this.completedStatus = completedStatus;
	}

}