package com.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Property implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "Customer")
	private com.solarvillage.Customer customer;
	@org.kie.api.definition.type.Label(value = "Address")
	private java.lang.String address;
	@org.kie.api.definition.type.Label(value = "Postcode")
	private java.lang.String postcode;

	public Property() {
	}

	public com.solarvillage.Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(com.solarvillage.Customer customer) {
		this.customer = customer;
	}

	public java.lang.String getAddress() {
		return this.address;
	}

	public void setAddress(java.lang.String address) {
		this.address = address;
	}

	public java.lang.String getPostcode() {
		return this.postcode;
	}

	public void setPostcode(java.lang.String postcode) {
		this.postcode = postcode;
	}

	public Property(com.solarvillage.Customer customer,
			java.lang.String address, java.lang.String postcode) {
		this.customer = customer;
		this.address = address;
		this.postcode = postcode;
	}

}