package com.solarvillage;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ResidentialPermit implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("Status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label("Permit No.")
	private java.lang.Integer id;

	public ResidentialPermit() {
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.Integer getId() {
		return this.id;
	}

	public void setId(java.lang.Integer id) {
		this.id = id;
	}

	public ResidentialPermit(java.lang.String status, java.lang.Integer id) {
		this.status = status;
		this.id = id;
	}

}